FROM node:20 AS buildenv
WORKDIR /app
COPY package*.json ./
RUN yarn global add @quasar/cli
RUN yarn global add dotenv
COPY . .

ARG BASE_URL
ENV BASE_URL=${BASE_URL}

RUN yarn
RUN quasar build
FROM nginx:1.23.1
COPY --from=buildenv app/dist/spa /usr/share/nginx/html
COPY default.conf /etc/nginx/conf.d/default.conf
