version: '3.8'
networks:
  signbank:
    driver: bridge

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.test
      args:
        DATABASE_URL: ${DATABASE_URL}
        ADMIN_EMAIL: ${ADMIN_EMAIL}
        ADMIN_PASSWORD: ${ADMIN_PASSWORD}
    container_name: backend-test
    environment:
      - PORT=80
      - DATABASE_URL=${DATABASE_URL}
      - TYPESENSE_API_KEY=${TYPESENSE_API_KEY}
      - ADMIN_EMAIL=${ADMIN_EMAIL}
      - ADMIN_PASSWORD=${ADMIN_PASSWORD}
      - BASE_URL=${BASE_URL}
    networks:
      - signbank
    restart: always
    depends_on:
      - mongoDB
      - typesense
    
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.test
      args:
        BASE_URL: ${BASE_URL}
    container_name: frontend-test
    environment:
      - BASE_URL=${BASE_URL}
    networks:
      - signbank    
    restart: always

  postgres:
    image: postgres:16
    container_name: postgres-test
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      POSTGRES_DB: ${POSTGRES_DB:-signbank_test}
    networks:
      - signbank
    volumes:
      - postgres_test_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: always

  typesense:
    image: typesense/typesense:27.1
    restart: always
    container_name: typesense-test
    environment:
      - TYPESENSE_API_KEY=${TYPESENSE_API_KEY}
      - TYPESENSE_DATA_DIR=/data
    networks:
      - signbank
    volumes:
      - typesense_data:/data
    command: '--data-dir /data --api-key=${TYPESENSE_API_KEY} --enable-cors'

  dufs:
    image: sigoden/dufs
    container_name: dufs-test
    volumes:
      - ./FileServer:/data
    command: /data -A
    restart: always
    networks:
      - signbank

  nginx:
    image: nginx:latest
    container_name: nginx-test
    ports:
      - "80:80"
      - "443:443"

    volumes:
      - ./nginx/nginx.test.conf/default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./nginx/certs:/etc/ssl/certs/
    networks:
      - signbank
    depends_on:
      - backend
      - frontend
    restart: always

volumes:
  postgres_test_data:
  typesense_data:
