version: '3.8'
networks:
  app_network:
    driver: bridge

services:
  backend:
    build:
      context: ./apps/backend
      dockerfile: Dockerfile.local
    container_name: backend
    environment:
      - DATABASE_HOST=db
      - DATABASE_PORT=5432
      - DATABASE_USER=postgres
      - DATABASE_PASSWORD=password
      - DATABASE_NAME=postgres
      - PORT=80
    networks:
      - app_network
    volumes:
      - ./apps/backend:/app
    depends_on:
      - db
      - typesense

  frontend:
    build:
      context: ./apps/frontend
      dockerfile: Dockerfile.local
    container_name: frontend
    networks:
      - app_network    

  db:
    build:
      context: ./apps/database
      dockerfile: Dockerfile.local
    image: postgres:15
    container_name: db
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    networks:
      - app_network
    volumes:
      - ./apps/database/data:/var/lib/postgresql/data
    ports:
      - 5432:5432

  typesense:
    image: typesense/typesense:27.1
    restart: on-failure
    container_name: typesense
    environment:
      - TYPESENSE_API_KEY=xyz123
      - TYPESENSE_DATA_DIR=/data
    networks:
      - app_network
    volumes:
      - ./apps/typesense/typesense_data:/data
    command: '--data-dir /data --api-key=xyz123 --enable-cors'


  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./apps/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    networks:
      - app_network

volumes:
  database:
  typesense_data:
