version: '3.8'
networks:
  signbank:
    driver: bridge

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.local
    container_name: backend
    environment:
      - PORT=443
      - DATABASE_URL=${DATABASE_URL}
      - TYPESENSE_API_KEY=${TYPESENSE_API_KEY}
      - BASE_URL=${BASE_URL}
    ports:
      - 9229:9229
    cap_add:
      - NET_BIND_SERVICE
    networks:
      - signbank
    volumes:
      - ./backend:/app
      - /app/node_modules #Exclude node_modules directory
    depends_on:
      - mongoDB
      - typesense
    
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.local
    container_name: frontend
    environment:
      - BASE_URL=${BASE_URL}
    networks:
      - signbank    
    volumes:
      - ./frontend:/app
      - /app/node_modules #Exclude node_modules directory

  # postgres:
  #   build:
  #     context: ./database
  #     dockerfile: Dockerfile.local
  #   image: postgres:15
  #   container_name: postgres
  #   environment:
  #     POSTGRES_PASSWORD: password
  #     POSTGRES_USER: postgres
  #     POSTGRES_DB: postgres
  #     POSTGRES_HOST_AUTH_METHOD: trust
  #   networks:
  #     - signbank
  #   volumes:
  #     - ./database/data:/var/lib/postgresql/data
  #   ports:
  #     - 5432:5432
  mongodb:
    build:
      context: ./mongoDB
      dockerfile: Dockerfile
    image: signbank-mongodb:latest
    container_name: mongoDB
    hostname: mongoDB
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
      DATABASE_URL: ${DATABASE_URL}
    networks:
      - signbank
    volumes:
      - ./mongoDB/data:/data/db
    ports:
      - 27017:27017
  typesense:
    image: typesense/typesense:27.1
    restart: on-failure
    container_name: typesense
    environment:
      - TYPESENSE_API_KEY=${TYPESENSE_API_KEY}
      - TYPESENSE_DATA_DIR=/data
    networks:
      - signbank
    volumes:
      - ./typesense/typesense_data:/data
    command: '--data-dir /data --api-key=${TYPESENSE_API_KEY} --enable-cors'
  dufs:
    image: sigoden/dufs
    volumes:
      - ./FileServer:/data
    command: /data -A
    restart: always
    networks:
      - signbank

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    environment:
      - BASE_URL=${BASE_URL}
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./nginx/certs:/etc/ssl/certs/
    networks:
      - signbank
    depends_on:
      - backend


volumes:
  database:
  typesense_data:
