version: '3.8'
networks:
  signbank:
    driver: bridge

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.local
    container_name: backend
    environment:
      - PORT=443
      - DATABASE_URL=${DATABASE_URL_DOCKER}
      - TYPESENSE_API_KEY=${TYPESENSE_API_KEY}
      - BASE_URL=${BASE_URL}
      - DUFS_URL=${DUFS_URL}
      - TYPESENSE_HOST=${TYPESENSE_HOST}
      - TYPESENSE_PORT=${TYPESENSE_PORT}
    ports:
      - 9229:9229
    cap_add:
      - NET_BIND_SERVICE
    networks:
      - signbank
    volumes:
      - ./backend:/app
      - /app/node_modules #Exclude node_modules directory
    depends_on:
      - typesense
      - postgres
    
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.local
    container_name: frontend
    environment:
      - BASE_URL=${BASE_URL}
    networks:
      - signbank    
    volumes:
      - ./frontend:/app
      - /app/node_modules #Exclude node_modules directory

  postgres:
    image: postgres:16
    container_name: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      POSTGRES_DB: ${POSTGRES_DB:-signbank}
    networks:
      - signbank
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  typesense:
    image: typesense/typesense:27.1
    restart: on-failure
    container_name: typesense
    environment:
      - TYPESENSE_API_KEY=${TYPESENSE_API_KEY}
      - TYPESENSE_DATA_DIR=/data
    networks:
      - signbank
    volumes:
      - ./typesense/typesense_data:/data
    command: '--data-dir /data --api-key=${TYPESENSE_API_KEY} --enable-cors'
  dufs:
    image: sigoden/dufs
    volumes:
      - ./FileServer:/data
    command: /data -A
    restart: always
    networks:
      - signbank

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./nginx/certs:/etc/ssl/certs/
    networks:
      - signbank
    depends_on:
      - backend


volumes:
  postgres_data:
  typesense_data:
