FROM node:20 AS builder

WORKDIR /app
COPY package*.json ./
COPY . .

RUN npm install
RUN npm run build

FROM node:20-alpine

WORKDIR /app

COPY --from=builder /app/dist ./dist
COPY --from=builder /app/node_modules ./node_modules
COPY --from=builder /app/package*.json ./
COPY --from=builder /app/prisma ./prisma
COPY --from=builder /app/docker-entrypoint.sh ./docker-entrypoint.sh

ENV NODE_ENV=test
ENV PORT=80

RUN addgroup -S appgroup && adduser -S appuser -G appgroup && \
    chmod +x /app/docker-entrypoint.sh && \
    sed -i 's/\r$//' /app/docker-entrypoint.sh

USER appuser

CMD ["/app/docker-entrypoint.sh", "npm", "run", "start:prod"]
