FROM node:22-alpine

WORKDIR /app
COPY package*.json ./

ENV DATABASE_URL="postgresql://postgres:password@db:5432/postgres?schema=public"

RUN npm install
COPY . .
RUN npx prisma migrate deploy

CMD ["npm", "run", "start:dev"]