version: '3.8'
services:
  postgres:
    image: postgres:16
    container_name: signbank-postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: signbank
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: 