-- Add missing enum values
ALTER TYPE "ConfigurationChange" ADD VALUE 'EMPTY';
ALTER TYPE "ContactType" ADD VALUE 'EMPTY';
ALTER TYPE "HandConfiguration" ADD VALUE 'EMPTY';
ALTER TYPE "Location" ADD VALUE 'EMPTY';
ALTER TYPE "MovementRelatedOrientation" ADD VALUE 'EMPTY';
ALTER TYPE "MovementType" ADD VALUE 'EMPTY';
ALTER TYPE "OrientationChange" ADD VALUE 'EMPTY';
ALTER TYPE "OrientationRelatedToLocation" ADD VALUE 'EMPTY';
ALTER TYPE "RelationBetweenArticulators" ADD VALUE 'EMPTY';
ALTER TYPE "RelationType" ADD VALUE 'HOMONYM';
ALTER TYPE "RelationType" ADD VALUE 'VARIANT';

-- Create MovementDirection enum
CREATE TYPE "MovementDirection" AS ENUM ('EMPTY', 'BACKWARDS', 'BACKWARDS_AND_CONTRALATERAL', 'BACKWARDS_AND_DOWNWARDS', 'BACKWARDS_AND_IPSILATERAL', 'BACKWARDS_AND_UPWARDS', 'BACKWARDS_TO_DOWNWARDS', 'BACKWARDS_TO_FORWARDS', 'BACKWARDS_OR_FORWARDS', 'CONTRALATERAL', 'CONTRALATERAL_AND_DOWNWARDS', 'CONTRALATERAL_AND_FORWARDS', 'CONTRALATERAL_AND_UPWARDS', 'CONTRALATERAL_TO_FORWARDS', 'CONTRALATERAL_TO_IPSILATERAL', 'DISTAL', 'DOWNWARDS', 'DOWNWARDS_AND_CONTRALATERAL_OR_IPSILATERAL', 'DOWNWARDS_AND_FORWARDS', 'DOWNWARDS_AND_IPSILATERAL', 'DOWNWARDS_AND_IPSILATERAL_TO_DOWNWARDS', 'DOWNWARDS_AND_TOWARDS', 'DOWNWARDS_TO_CONTRALATERAL', 'DOWNWARDS_TO_FORWARDS', 'DOWNWARDS_TO_IPSILATERAL', 'DOWNWARDS_TO_UPWARDS', 'DOWNWARDS_OR_UPWARDS', 'DOWNWARDS_OR_UPWARDS_AND_IPSILATERAL', 'FORWARDS', 'FORWARDS_AND_IPSILATERAL', 'FORWARDS_AND_UPWARDS', 'FORWARDS_TO_BACKWARDS', 'FORWARDS_TO_CONTRALATERAL', 'FORWARDS_TO_DOWNWARDS', 'FORWARDS_TO_IPSILATERAL', 'FORWARDS_TO_IPSILATERAL_TO_FORWARDS', 'FORWARDS_TO_UPWARDS', 'FROM_LOCATION', 'IPSILATERAL', 'IPSILATERAL_AND_UP_AND_DOWN', 'IPSILATERAL_AND_UPWARDS', 'IPSILATERAL_TO_CONTRALATERAL', 'IPSILATERAL_TO_DOWNWARDS', 'IPSILATERAL_TO_DOWNWARDS_TO_CONTRALATERAL', 'IPSILATERAL_TO_UPWARDS', 'IPSILATERAL_AND_CONTRALATERAL', 'IPSILATERAL_OR_CONTRALATERAL', 'LATERAL', 'PROXIMAL', 'TO_AND_FRO', 'TOWARDS_LOCATION', 'UP_AND_DOWN', 'UPWARDS', 'UPWARDS_TO_DOWNWARDS', 'UPWARDS_TO_FORWARDS_TO_DOWNWARDS', 'UPWARDS_TO_IPSILATERAL', 'VARIABLE', 'FORWARDS_AND_DOWNWARDS', 'CONTRALATERAL_TO_DOWNWARDS', 'DOWNWARDS_TO_CONTRALATERAL_TO_IPSILATERAL', 'UPWARDS_AND_FORWARDS', 'IPSILATERAL_TO_FORWARDS', 'IPSILATERAL_TO_BACKWARDS_TO_CONTRALATERAL', 'IPSILATERAL_AND_DOWNWARDS');

-- Add missing columns to User table
ALTER TABLE "User" ADD COLUMN "name" TEXT;
ALTER TABLE "User" ADD COLUMN "lastName" TEXT;

-- Add missing column to Definition table
ALTER TABLE "Definition" ADD COLUMN "priority" INTEGER NOT NULL DEFAULT 0;

-- Add missing columns to VideoData table
ALTER TABLE "VideoData" ADD COLUMN "movementDirection" "MovementDirection" NOT NULL DEFAULT 'EMPTY';
ALTER TABLE "VideoData" ADD COLUMN "repeatedMovement" BOOLEAN NOT NULL DEFAULT false;

-- Add missing columns to SignVideo table
ALTER TABLE "SignVideo" ADD COLUMN "glossDataId" TEXT;

-- Add foreign key constraint for SignVideo.glossDataId
ALTER TABLE "SignVideo" ADD CONSTRAINT "SignVideo_glossDataId_fkey" FOREIGN KEY ("glossDataId") REFERENCES "GlossData"("id") ON DELETE CASCADE ON UPDATE CASCADE; 